import type { TGenericComponentRegistry } from "@/types/elements/elements";
import { Button } from "../ui/button";
import {
  PanelsTopLeft,
  SquareGanttChartIcon,
  SquareMousePointer,
  SquareSlash,
} from "lucide-react";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "../ui/card";
import Root from "./Root";

export const Registry: TGenericComponentRegistry = {
  Root: {
    type: "Root",
    icon: <PanelsTopLeft />,
    component: <Root />,
    dependencies: [],
    draggable: false,
    droppable: true,
    editable: false,
    classNameGroups: ["Size", "Layout"],
  },
  div: {
    type: "div",
    icon: <SquareGanttChartIcon />,
    component: <div />,
    dependencies: [],
    draggable: true,
    droppable: true,
    editable: false,
    classNameGroups: ["Size", "Layout"],
  },
  span: {
    type: "span",
    icon: <SquareGanttChartIcon />,
    component: <span />,
    dependencies: [],
    draggable: true,
    droppable: true,
    editable: true,
    classNameGroups: [],
  },
  h1: {
    type: "h1",
    icon: <SquareGanttChartIcon />,
    // biome-ignore lint/a11y/useHeadingContent: <explanation>
    component: <h1 />,
    dependencies: [],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: [],
  },
  h2: {
    type: "h2",
    icon: <SquareGanttChartIcon />,
    // biome-ignore lint/a11y/useHeadingContent: <explanation>
    component: <h2 />,
    dependencies: [],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: [],
  },
  h3: {
    type: "h3",
    icon: <SquareGanttChartIcon />,
    // biome-ignore lint/a11y/useHeadingContent: <explanation>
    component: <h3 />,
    dependencies: [],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: [],
  },
  h4: {
    type: "h4",
    icon: <SquareGanttChartIcon />,
    // biome-ignore lint/a11y/useHeadingContent: <explanation>
    component: <h4 />,
    dependencies: [],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: [],
  },
  h5: {
    type: "h5",
    icon: <SquareGanttChartIcon />,
    // biome-ignore lint/a11y/useHeadingContent: <explanation>
    component: <h5 />,
    dependencies: [],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: [],
  },
  h6: {
    type: "h6",
    icon: <SquareGanttChartIcon />,
    // biome-ignore lint/a11y/useHeadingContent: <explanation>
    component: <h6 />,
    dependencies: [],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: [],
  },
  p: {
    type: "p",
    icon: <SquareGanttChartIcon />,
    component: <p />,
    dependencies: [],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: [],
  },
  Card: {
    type: "Card",
    icon: <SquareSlash />,
    component: <Card />,
    dependencies: ["@/components/ui/Card"],
    draggable: true,
    droppable: true,
    editable: false,
    classNameGroups: [],
  },
  CardContent: {
    type: "CardContent",
    icon: <SquareSlash />,
    component: <CardContent />,
    dependencies: ["@/components/ui/CardContent"],
    draggable: true,
    droppable: true,
    editable: false,
    classNameGroups: [],
  },
  CardHeader: {
    type: "CardHeader",
    icon: <SquareSlash />,
    component: <CardHeader />,
    dependencies: ["@/components/ui/CardHeader"],
    draggable: true,
    droppable: true,
    editable: false,
    classNameGroups: [],
  },
  CardFooter: {
    type: "CardFooter",
    icon: <SquareSlash />,
    component: <CardFooter />,
    dependencies: ["@/components/ui/CardFooter"],
    draggable: true,
    droppable: true,
    editable: false,
    classNameGroups: [],
  },
  CardTitle: {
    type: "CardTitle",
    icon: <SquareSlash />,
    component: <CardTitle />,
    dependencies: ["@/components/ui/CardTitle"],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: [],
  },
  CardDescription: {
    type: "CardDescription",
    icon: <SquareSlash />,
    component: <CardDescription />,
    dependencies: ["@/components/ui/CardDescription"],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: [],
  },
  Button: {
    type: "Button",
    icon: <SquareMousePointer />,
    component: <Button />,
    dependencies: ["@/components/ui/Button"],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: [],
  },
} as const;
