import type { TGenericComponentRegistry } from "@/types/elements/elements";
import { Button } from "../ui/button";
import {
  PanelsTopLeft,
  Square,
  SquareGanttChartIcon,
  SquareMousePointer,
  SquareSlash,
  Text,
  Type,
} from "lucide-react";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "../ui/card";
import Root from "./Root";

export const Registry: TGenericComponentRegistry = {
  Root: {
    type: "Root",
    icon: <PanelsTopLeft />,
    component: <Root />,
    dependencies: [],
    draggable: false,
    droppable: true,
    editable: false,
    classNameGroups: {
      size: {
        name: "size",
        disabled: true,
      },
    },
    defaultClassNameProperties: {
      height: "h-screen",
      width: "w-screen",
    },
  },
  div: {
    type: "div",
    icon: <Square />,
    component: <div />,
    dependencies: [],
    draggable: true,
    droppable: true,
    editable: false,
    classNameGroups: {
      size: {
        name: "size",
      },
      layout: {
        name: "layout",
      },
    },
    defaultClassNameProperties: {
      height: "h-auto",
      width: "w-full",
      padding: "p-0",
      gap: "gap-0",
      display: "block",
      flexDirection: "flex-row",
      justifyContent: "justify-start",
      alignItems: "items-start",
      gridTemplateColumns: "grid-cols-1",
      gridTemplateRows: "grid-rows-1",
    },
  },
  span: {
    type: "span",
    icon: <SquareGanttChartIcon />,
    component: <span />,
    dependencies: [],
    draggable: true,
    droppable: true,
    editable: true,
    classNameGroups: {},
    defaultClassNameProperties: {},
  },
  h1: {
    type: "h1",
    icon: <Type />,
    // biome-ignore lint/a11y/useHeadingContent: <explanation>
    component: <h1 />,
    dependencies: [],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: {},
    defaultClassNameProperties: {},
  },
  h2: {
    type: "h2",
    icon: <Type />,
    // biome-ignore lint/a11y/useHeadingContent: <explanation>
    component: <h2 />,
    dependencies: [],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: {},
    defaultClassNameProperties: {},
  },
  h3: {
    type: "h3",
    icon: <Type />,
    // biome-ignore lint/a11y/useHeadingContent: <explanation>
    component: <h3 />,
    dependencies: [],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: {},
    defaultClassNameProperties: {},
  },
  h4: {
    type: "h4",
    icon: <Type />,
    // biome-ignore lint/a11y/useHeadingContent: <explanation>
    component: <h4 />,
    dependencies: [],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: {},
    defaultClassNameProperties: {},
  },
  h5: {
    type: "h5",
    icon: <Type />,
    // biome-ignore lint/a11y/useHeadingContent: <explanation>
    component: <h5 />,
    dependencies: [],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: {},
    defaultClassNameProperties: {},
  },
  h6: {
    type: "h6",
    icon: <Type />,
    // biome-ignore lint/a11y/useHeadingContent: <explanation>
    component: <h6 />,
    dependencies: [],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: {},
    defaultClassNameProperties: {},
  },
  p: {
    type: "p",
    icon: <Text />,
    component: <p />,
    dependencies: [],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: {},
    defaultClassNameProperties: {},
  },
  Card: {
    type: "Card",
    icon: <SquareSlash />,
    component: <Card />,
    dependencies: ["@/components/ui/Card"],
    draggable: true,
    droppable: true,
    editable: false,
    classNameGroups: {},
    defaultClassNameProperties: {},
  },
  CardContent: {
    type: "CardContent",
    icon: <SquareSlash />,
    component: <CardContent />,
    dependencies: ["@/components/ui/CardContent"],
    draggable: true,
    droppable: true,
    editable: false,
    classNameGroups: {},
    defaultClassNameProperties: {},
  },
  CardHeader: {
    type: "CardHeader",
    icon: <SquareSlash />,
    component: <CardHeader />,
    dependencies: ["@/components/ui/CardHeader"],
    draggable: true,
    droppable: true,
    editable: false,
    classNameGroups: {},
    defaultClassNameProperties: {},
  },
  CardFooter: {
    type: "CardFooter",
    icon: <SquareSlash />,
    component: <CardFooter />,
    dependencies: ["@/components/ui/CardFooter"],
    draggable: true,
    droppable: true,
    editable: false,
    classNameGroups: {},
    defaultClassNameProperties: {},
  },
  CardTitle: {
    type: "CardTitle",
    icon: <SquareSlash />,
    component: <CardTitle />,
    dependencies: ["@/components/ui/CardTitle"],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: {},
    defaultClassNameProperties: {},
  },
  CardDescription: {
    type: "CardDescription",
    icon: <SquareSlash />,
    component: <CardDescription />,
    dependencies: ["@/components/ui/CardDescription"],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: {},
    defaultClassNameProperties: {},
  },
  Button: {
    type: "Button",
    icon: <SquareMousePointer />,
    component: <Button />,
    dependencies: ["@/components/ui/Button"],
    draggable: true,
    droppable: false,
    editable: true,
    classNameGroups: {},
    defaultClassNameProperties: {},
  },
} as const;
