import type { TailwindStylePropertyName } from "@/types/tailwind/tailwind";
import {
	FONT_SIZE_CLASSNAMES,
	FONT_WEIGHT_CLASSNAMES,
	TEXT_ALIGN_CLASSNAMES,
	TEXT_COLOR_CLASSNAMES_FLAT,
} from "./text";
import { BACKGROUND_COLOR_CLASSNAMES_FLAT } from "./background";
import {
	WIDTH_CLASSNAMES,
	HEIGHT_CLASSNAMES,
	BORDER_RADIUS_CLASSNAMES,
} from "./size";
import {
	DISPLAY_CLASSNAMES,
	FLEX_DIRECTION_CLASSNAMES,
	JUSTIFY_CONTENT_CLASSNAMES,
	ALIGN_ITEMS_CLASSNAMES,
	GRID_TEMPLATE_COLUMNS_CLASSNAMES,
	GRID_TEMPLATE_ROWS_CLASSNAMES,
	GAP_CLASSNAMES,
} from "./layout";
import {
	PADDING_CLASSNAMES,
	PADDING_X_CLASSNAMES,
	PADDING_Y_CLASSNAMES,
	PADDING_LEFT_CLASSNAMES,
	PADDING_RIGHT_CLASSNAMES,
	PADDING_TOP_CLASSNAMES,
	PADDING_BOTTOM_CLASSNAMES,
} from "./padding";
import {
	MARGIN_CLASSNAMES,
	MARGIN_X_CLASSNAMES,
	MARGIN_Y_CLASSNAMES,
	MARGIN_LEFT_CLASSNAMES,
	MARGIN_RIGHT_CLASSNAMES,
	MARGIN_TOP_CLASSNAMES,
	MARGIN_BOTTOM_CLASSNAMES,
} from "./margin";

export const PROPERTIES_CLASSNAMES: {
	[key in TailwindStylePropertyName]: string[];
} = {
	width: WIDTH_CLASSNAMES,
	height: HEIGHT_CLASSNAMES,
	display: DISPLAY_CLASSNAMES,
	flexDirection: FLEX_DIRECTION_CLASSNAMES,
	justifyContent: JUSTIFY_CONTENT_CLASSNAMES,
	alignItems: ALIGN_ITEMS_CLASSNAMES,
	gridTemplateColumns: GRID_TEMPLATE_COLUMNS_CLASSNAMES,
	gridTemplateRows: GRID_TEMPLATE_ROWS_CLASSNAMES,
	gap: GAP_CLASSNAMES,
	textAlign: TEXT_ALIGN_CLASSNAMES,
	textColor: TEXT_COLOR_CLASSNAMES_FLAT,
	fontSize: FONT_SIZE_CLASSNAMES,
	fontWeight: FONT_WEIGHT_CLASSNAMES,
	backgroundColor: BACKGROUND_COLOR_CLASSNAMES_FLAT,
	padding: PADDING_CLASSNAMES,
	paddingX: PADDING_X_CLASSNAMES,
	paddingY: PADDING_Y_CLASSNAMES,
	paddingLeft: PADDING_LEFT_CLASSNAMES,
	paddingRight: PADDING_RIGHT_CLASSNAMES,
	paddingTop: PADDING_TOP_CLASSNAMES,
	paddingBottom: PADDING_BOTTOM_CLASSNAMES,
	margin: MARGIN_CLASSNAMES,
	marginX: MARGIN_X_CLASSNAMES,
	marginY: MARGIN_Y_CLASSNAMES,
	marginLeft: MARGIN_LEFT_CLASSNAMES,
	marginRight: MARGIN_RIGHT_CLASSNAMES,
	marginTop: MARGIN_TOP_CLASSNAMES,
	marginBottom: MARGIN_BOTTOM_CLASSNAMES,
	borderRadius: BORDER_RADIUS_CLASSNAMES,
};

export * from "./text";
export * from "./background";
export * from "./size";
export * from "./layout";
export * from "./padding";
export * from "./margin";
